name: AI-Spy Weekly

on:
  schedule:
    - cron: '0 7 * * 1'  # Maandag 09:00 NL-tijd (07:00 UTC)
  workflow_dispatch:      # Handmatig starten via GitHub

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run AI-Spy
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
